/*
    Author: Brady Lamson, Milah Thomas
    Date: July 2nd, 2021
    BradyLamson_001_02 replicates a basic scientific calculator. Takes in user
        input, does a small handful of calculations and provides a
        report of calculations done at the end of the program.
    Project #2
    IDE: IntelliJ IDEA 2021.1.2 (Community Edition)
    Vocabulary Word: Dragoman. Noun.
        An interpreter or professional guide for travellers, especially one in
        countries in which Arabic, Turkish, or Persian is spoken.
        Source: Lexico.com/explore/weird-and-wonderful-words    Inspirational Quote:
        "It's out of problems that you can't understand that you make progress.
        Doing science means bumping into something that makes you wonder, that
        you don't know the answer to, and in getting to the answer brings you
        to an understanding of the bigger world around us."
        - Clifford Stoll. (b. 1950)
*/

// Imports ********************************************************************
import java.text.DecimalFormat;
import java.util.Scanner;

// Begin class BradyLamson_001_02 *********************************************
public class BradyLamson_001_02 {
    // General variable declarations ------------------------------------------
    /*
         These 'count' variables are counters for each method.
         Every time one is used, they increment up by one.
         They'll be utilized in the report at the end of the program.
    */
    private int minCount;
    private int maxCount;
    private int powerCount;
    private int absoluteCount;
    private final Scanner scan = new Scanner(System.in);    // Access keyboard
    // End general variable declarations --------------------------------------

    // main method ************************************************************
    public static void main(String[] args) {
        BradyLamson_001_02 myCalculator = new BradyLamson_001_02();
        printIntro();
        myCalculator.calculate();
        myCalculator.printReport();
    }   // End main

    // Default Constructor ****************************************************
    public BradyLamson_001_02(){
        // This is the default constructor and sets all of the necessary
        // variables to default values.
        minCount = 0;
        maxCount = 0;
        powerCount = 0;
        absoluteCount = 0;
    }   // End default constructor

    // print intro method *****************************************************
    public static void printIntro() {
        // This prints out a simple introduction on how the program works.
        System.out.println(
                "\nThis program is a simple scientific calculator. You can "
                + "choose from four different operations. \n"
                + "The operations are minimum, maximum, power and "
                + "absolute value. \n" );
    }   // End printIntro()

    // computeOperation method ************************************************
    private void computeOperation(String initOperation)  {
        /*
            This method handles the actual computation and printing of answers.
            It uses a scanner to generate two numbers and, depending on the
            specified operation, uses different 'Math' methods.
         */

        // Local variable declarations ----------------------------------------
        double userNumber1;         // First variable input via scanner.
        double userNumber2 = 0;     // Second variable input via scanner.
        double answer = 0;          // Answer generated by 'Math.' methods.
        DecimalFormat formatter = new DecimalFormat("#,###.00");
        /*
            For decimalFormat, the "#.00" mandates that even if a number has
            less than 2 decimals, it puts 0s at the end.
            For example, '2' becomes '2.00'.

            End of local variable declarations ---------------------------------

            - This section prints out the chosen operation and assigns
              two variables input via a scanner.
            - If Operation is "absolute value" only one number is scanned in.
            - Depending on "initOperation", different calculations are done
              using those variables.
        */

        if (initOperation.equals("absolute value")) {
            System.out.println("\nYou selected " + initOperation + ".\n"
                    + "Enter your number: ");
            userNumber1 = scan.nextDouble();
        }   // End if
        else {
            // All other cases need two variables.
            System.out.println("\nYou selected " + initOperation + ".\n"
                    + "Enter your first number:");
            userNumber1 = scan.nextDouble();
            System.out.println("Enter your second number:");
            userNumber2 = scan.nextDouble();
        }   // End else

        switch (initOperation) {
            case "minimum":
                answer = Math.min(userNumber1, userNumber2);
                break;
            case "maximum":
                answer = Math.max(userNumber1, userNumber2);
                break;
            case "power":
                answer = Math.pow(userNumber1, userNumber2);
                break;
            case "absolute value":
                answer = Math.abs(userNumber1);
                break;
        }   // End switch()

        System.out.println("The answer is "
                + formatter.format(answer)
                + "\n");
    }   // End computeOperation

    // calculate method *******************************************************
    public void calculate(){
        /*
            General idea for this method is to use the scanner to pick an
            operation. A letter corresponds to each. "N" picks minimum, as an
            example. Depending on which letter used we enter into a specific
            case which uses the computeOperation() method. This is also where
            we increment up our counters.
            This loops until "T" is chosen, where we then exit this method.
         */

        // Local variable declarations ----------------------------------------
        String userInput;
        String chosenOperation;
        boolean askAgain = true;  // This variable is used to run our loop.
                                  // We keep it true until "T" is chosen.
        // End of local variable declarations ---------------------------------

        while(askAgain) {         // This is equivalent to "while(ask == true)"
            System.out.print(
                    "Select the problem type you want to calculate by entering"
                    + " the first letter of the operation. \n"
                    + "(N) Minimum of two numbers. \n"
                    + "(X) Maximum of two numbers. \n"
                    + "(P) First operand raised to the power of the second "
                    + "operand. \n"
                    + "(A) Find the absolute value of a number. \n"
                    + "\n"
                    + "(T) Display total Counts, then exit the program. \n"
                    + "\n"
                    + "Operation? ");
            userInput = scan.next();
            // I want to convert input to uppercase to reduce the number of
            // cases I need to test for.
            chosenOperation = userInput.toUpperCase();

            // Depending on value of chosenOperation different versions of
            // computeOperation() are utilized.
            // chosenOperation value of "T" exits the loop.
            switch (chosenOperation)  {
                case "N":
                    computeOperation("minimum");
                    minCount++;
                    break;
                case "X":
                    computeOperation("maximum");
                    maxCount++;
                    break;
                case "P":
                    computeOperation("power");
                    powerCount++;
                    break;
                case "A":
                    computeOperation("absolute value");
                    absoluteCount++;
                    break;
                case "T":
                    // I use "T" as an exit to the loop.
                    askAgain = false;
                    break;
                default:
                    System.out.println("Please input a valid character to "
                            + "select an operation.\n");
                    break;
            }   // End switch()
        }   // End while()
    }   // End calculate()

    // print report method ****************************************************
    public void printReport() {
        // This method prints a report of operations used.

        // Note: "this." allows me to reference members of the current object.
        int totalCount = this.maxCount      // Total of the method counters.
                + this.minCount
                + this.powerCount
                + this.absoluteCount;

        /*
            - Below if statements ensure that the various counts only print if
                they were utilized by the user.
            - 'if' used instead of 'if else' to ensure multiple statements
                can be true.
            - Total count meanwhile will always print.
                This is mostly a matter of taste.
        */

        System.out.println("Calculator Report:");

        if (minCount > 0)   {
            System.out.println("Minimum Problems: " + minCount);
        }   // End if

        if (maxCount > 0)   {
            System.out.println("Maximum Problems: " + maxCount);
        }   // End if

        if (powerCount > 0) {
            System.out.println("Power Problems: " + powerCount);
        }   // End if

        if (absoluteCount > 0)  {
            System.out.println("Absolute Value Problems: " + absoluteCount);
        }   // End if

        System.out.println("Total number of calculations done: " + totalCount);
    }   // End printReport()
}   // End class BradyLamson_001_02